server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /products {
        proxy_pass http://product-service:8000;
    }

    location /orders {
        proxy_pass http://order-service:8001;
    }
}
